import BillPayModal from '@/Components/BillPayModal';
import '@/Styles/tailwindcss.css';
import '@/Styles/Typography.css';


//component
import { Plus_Jakarta_Sans } from "next/font/google";
import { Suspense } from 'react';


// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={``}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

export const metadata = {
  title: "Payppy",
  description: "Payppy.app — India’s First Fashion Fintech for Gen Z",
 viewport: "width=device-width, initial-scale=1.0",
};


const plus_jakarta_sans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  display: 'swap'
})

export default function RootLayout({ children }) {
  return (

      <html lang="en">
      <head>
        <link rel="icon" href="/icon.png" type="image/x-icon" />
      </head>
        <body className={" "+plus_jakarta_sans.className}>
          {children}
          {/* <PWAInstallPrompt/> */}
          <Suspense>
            <BillPayModal/>
          </Suspense>
        </body>
      </html>

  );
}
